#numpy

In [9]:
lst = [1,2,3,4,5,6]

In [11]:
_list = [1,2,3,4,5]

In [12]:
_list

[1, 2, 3, 4, 5]

In [13]:
_arr1d = np.array(list)

NameError: name 'np' is not defined

In [14]:
import numpy as np

In [17]:
_arr1d = np.array(_list)

In [18]:
_arr1d

array([1, 2, 3, 4, 5])

In [19]:
lst = [1,2,3,4,5,6]

In [20]:
lst

[1, 2, 3, 4, 5, 6]

In [21]:
import numpy as np

In [22]:
arr = np.array(lst)

In [23]:
arr

array([1, 2, 3, 4, 5, 6])

In [24]:
print(arr)

[1 2 3 4 5 6]


In [25]:
arr +2

array([3, 4, 5, 6, 7, 8])

In [26]:
print(arr*3)

[ 3  6  9 12 15 18]


In [27]:
arr2 = arr +arr

In [28]:
arr2

array([ 2,  4,  6,  8, 10, 12])

In [29]:
arr3 =arr-arr

In [30]:
arr3

array([0, 0, 0, 0, 0, 0])

In [31]:
print(type(_list))

<class 'list'>


In [32]:
print(type(arr))

<class 'numpy.ndarray'>


In [33]:
_arr1d.shape

(5,)

In [34]:
arr.shape

(6,)

In [35]:
my_list1 = [1,2,3,4,5]

In [36]:
my_list2 =[2,3,4,5,6]

In [38]:
my_list3 =[3,4,5,6,7]

In [39]:
arr = np.array([my_list1,my_list2,my_list3])

In [40]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [41]:
print(arr)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]]


In [42]:
type(arr)

numpy.ndarray

In [43]:
arr.shape

(3, 5)

In [44]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 3, 4],
       [5, 6, 7]])

In [45]:
arr.reshape(1,15)

array([[1, 2, 3, 4, 5, 2, 3, 4, 5, 6, 3, 4, 5, 6, 7]])

In [46]:
arr.reshape(15,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [2],
       [3],
       [4],
       [5],
       [6],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [ ]:
_